# Site settings
name: Onther's Publications
email: info@onther.io
author: Onther Inc.
url: http://www.hifreud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/Onther-Tech/
baseurl: ""
description: 이더리움 블록체인 R&D 스타트업 온더의 발간물
meta_description: 이더리움 블록체인 스타트업 온더의 발간물
motto: If you can't measure it—it doesn't exist.
banner: 블록체인이란 사회적 비용을 줄이기 위해 컴퓨팅 비용을 희생하는법에 관한 것이다 - V. Buterin

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: ggs134

# Build settings
markdown: kramdown

# baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
